WITH AVAIL_ID AS ( #11.1~11.30 대여 불가능한 CAR_ID
    SELECT DISTINCT CAR_ID, START_DATE, END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-01'
),
FILTER1 AS ( # SUV,세단의 30일 이상 레코드만 떼어오고, CAR_RENTAL_COMPANY_CAR 와 JOIN
    SELECT CAR_ID, C.CAR_TYPE, DAILY_FEE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ("세단", "SUV")
    AND DURATION_TYPE = "30일 이상"
)
SELECT CAR_ID, CAR_TYPE, ROUND(30* DAILY_FEE * (1 - (DISCOUNT_RATE/100)),0) FEE 
FROM FILTER1
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM AVAIL_ID)
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;