WITH
TOT_HALF AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOT
    FROM FIRST_HALF
    GROUP BY FLAVOR
),
TOT_JULY AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOT
    FROM JULY
    GROUP BY FLAVOR
),
TOTAL AS(
    SELECT H.FLAVOR, SUM(H.TOT+J.TOT) AS TOT_SUM 
    FROM TOT_HALF H 
    JOIN TOT_JULY J 
    ON H.FLAVOR = J.FLAVOR 
    GROUP BY H.FLAVOR
)
SELECT FLAVOR FROM TOTAL ORDER BY TOT_SUM DESC LIMIT 3;
