-- 코드를 입력하세요
# SELECT A2.HOUR, IFNULL(COUNT(A2.ANIMAL_ID),0) AS COUNT
# SELECT *
# FROM (SELECT ANIMAL_ID , (HOUR(DATETIME), 0) AS HOUR FROM ANIMAL_OUTS) AS A2
# GROUP BY A2.HOUR
# ORDER BY A2.HOUR


WITH RECURSIVE HOUR_LIST AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOUR_LIST
    WHERE HOUR < 23
)
SELECT H.HOUR, IFNULL(A.COUNT, 0) AS COUNT
FROM HOUR_LIST H
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT FROM ANIMAL_OUTS GROUP BY HOUR) A
ON H.HOUR = A.HOUR;
