-- 코드를 작성해주세요
# 16, 2048, 8192 
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, SKILLCODES S
WHERE S.CATEGORY = "Front End" AND S.CODE & D.SKILL_CODE = S.CODE
ORDER BY D.ID;
