-- 코드를 작성해주세요
WITH FILTER_YEAR AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT F.YEAR, (F.MAX_SIZE - E.SIZE_OF_COLONY) YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN FILTER_YEAR F
ON F.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY F.YEAR ASC, YEAR_DEV ASC;