-- 코드를 입력하세요
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, 
       (SELECT PRODUCT_NAME 
        FROM FOOD_PRODUCT F2 
        WHERE F2.CATEGORY = F1.CATEGORY AND F2.PRICE = MAX(F1.PRICE) 
        LIMIT 1) AS PRODUCT_NAME
FROM FOOD_PRODUCT F1
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;
